language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
before_install:
  - git clone git://github.com/rafael1193/GitHubRankingsFrance.git generated
script:
  - make
after_success:
  - git config --global user.email "rafael1193@zoho.com"
  - git config --global user.name "Rafael Bailon-Ruiz"
  - cd generated
  - git remote
  - git add -A .
  - git commit -m "Update rankings"
  - git push "https://rafael1193:${GH_ACCESS}@github.com/rafael1193/GitHubRankingsFrance.git" master > /dev/null 2>&1
