language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
before_install:
  - git clone git://github.com/rafael1193/GitHubRankingsFrance.git generated
script:
  - make
after_success:
  - echo "I should be pushing the results in the future..."
